name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.0'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        make setup-go
        make setup-python
        make setup-node

    - name: Build Go project
      run: |
        go build ./node/src/...  # Add your Go build command here
        make build-go

    - name: Run Go vet (Static Analysis)
      run: |
        go vet ./node/src/...   # Analyze the Go files

    - name: Run tests
      run: |
        make test-go
        make test-python

    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: |
          coverage.out
