name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.0'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler libprotobuf-dev

    - name: Set up Go cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('QuantumFuse_Blockchain/node/src/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Python cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('QuantumFuse_Blockchain/core/src/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Set up Node.js cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('QuantumFuse_Blockchain/quantumfuse_dapp/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        make setup-go
        make setup-python
        make setup-node

    - name: Build project
      run: |
        make build-go
        make build-python
        make build-node

    - name: Run tests
      run: |
        make test-go
        make test-python

    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: |
          coverage.out

    - name: Build Docker image
      run: make docker_build

    - name: Run Docker container
      run: make docker_run
      
